---
title: "Case study_Predictiton"
output: html_notebook
---

```{r}
library(dummies)
library(ggplot2)
library(car)
library(kader)
library(MASS)
library(scales)
library(psych)
library(e1071)
library(outliers)
library(rpart)
library(rpart.plot)
library(randomForest)
library(caret)
library(mgcv)
library(ROCR)
library(gains)
library(Metrics)
library(caTools)
library(e1071)
library(gmodels)
library(corrplot)
```


```{r Import cleaned data}
Music_=read.csv("spotifyclean.csv",
                stringsAsFactors=FALSE,na.strings = "")

Music=Music_[,-c(1,3,5,14)]


```


```{r}
#SAMPLING 50-30-20

set.seed(111)
#SAMPLING 50-30-20
set.seed(111)

train.index2 <- sample(row.names(Music), 0.5*dim(Music)[1])
valid_Test.index <- setdiff(row.names(Music), train.index2)

MusicTrain <- Music[train.index2,]
valid_Test.df <- Music[valid_Test.index,]


valid.index2 <- sample(row.names(valid_Test.df),
                        0.6*dim(valid_Test.df)[1])
test.index2 <- setdiff(row.names(valid_Test.df),
                        valid.index2)

MusicValid <- valid_Test.df[valid.index2,]
MusicTest <- valid_Test.df[test.index2,]


```




```{r Random forest }
rf <- randomForest(popularity~., data = MusicTrain)
rf
importance(rf)

rf.pred.train <- predict(rf, MusicTrain)
rf.pred.valid <- predict(rf, MusicValid)
rf.pred.test <- predict(rf, MusicTest)



#use rmse to evaluate the performance
RMSE(rf.pred.train, MusicTrain$popularity)#3.400
RMSE(rf.pred.valid, MusicValid$popularity)#7.839
RMSE(rf.pred.test, MusicTest$popularity)#7.549

#use MAE
MAE(rf.pred.train, MusicTrain$popularity) #2.66
MAE(rf.pred.valid, MusicValid$popularity)#6.21
MAE(rf.pred.test, MusicTest$popularity) #6.00

#MAPE
mape(rf.pred.train, MusicTrain$popularity) #0.047
mape(rf.pred.valid, MusicValid$popularity)#0.112
mape(rf.pred.test, MusicTest$popularity) #.108

#Use Mean error
me(rf.pred.train, MusicTrain$popularity)#0.086
me(rf.pred.valid, MusicValid$popularity)#0.319
me(rf.pred.test, MusicTest$popularity)#0.198


#The RMSE shows that this model is good.

```



```{r SVM}
mu.svm <- svm(Music[,-1], Music[,1])
data.frame(actual=Music[,1], predicted=mu.svm$fitted)


RMSE(mu.svm$fitted, Music$popularity)#7.58
me(mu.svm$fitted, Music$popularity) #-1.31
MAE(mu.svm$fitted, Music$popularity) #5.66
mape(mu.svm$fitted, Music$popularity) #0.104

```



```{r LDA}
Music2=Music_[,-c(1,3,5,2)]


set.seed(111)
train.indexm <- sample(row.names(Music2), 0.6*dim(Music2)[1])
valid_Test.indexm <- setdiff(row.names(Music2), train.indexm)

MusicTrain.cl <- Music2[train.indexm,]
MusicValid.cl <- Music2[valid_Test.indexm,]


mu.lda <- lda(popularcategory~., MusicTrain.cl)

mu.lda.pred <- predict(mu.lda, as.data.frame(MusicValid.cl[,-10]))
data.frame(actual=MusicValid.cl[,10], predicted=mu.lda.pred$class)

confusionMatrix(as.factor(MusicValid.cl$popularcategory), as.factor(mu.lda.pred$class))


lift.lda <- lift(relevel(as.factor(MusicValid.cl$popularcategory), ref="1") ~ mu.lda.pred$class)
xyplot(lift.lda, plot = "gain")

r <- roc(as.numeric(MusicValid.cl$popularcategory), as.numeric(mu.lda.pred$class))
plot.roc(r)

auc(r)


```


